trigger:
  branches:
    include:
    - refs/heads/master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false
  - task: ArchiveFiles@2
    displayName: Archive
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...
